"""Initial migration: create users, students, alumni tables

Revision ID: fddad4700bf9
Revises: 
Create Date: 2026-01-03 12:12:28.480062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fddad4700bf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ALUMNI', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_university_id'), 'users', ['university_id'], unique=False)
    op.create_table('alumni',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('current_role', sa.String(length=100), nullable=False),
    sa.Column('current_company', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('previous_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hobbies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interesting_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('availability_status', sa.Enum('OPEN', 'LIMITED', 'CLOSED', name='availabilitystatus'), nullable=False),
    sa.Column('request_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_requests_per_month', sa.Integer(), nullable=False),
    sa.Column('current_month_requests', sa.Integer(), nullable=False),
    sa.Column('helpfulness_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_introductions', sa.Integer(), nullable=False),
    sa.Column('response_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_response_time_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alumni_career', 'alumni', ['industry', 'current_role'], unique=False)
    op.create_index('idx_alumni_hobbies', 'alumni', ['hobbies'], unique=False, postgresql_using='gin')
    op.create_index('idx_alumni_interests', 'alumni', ['interests'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_alumni_availability_status'), 'alumni', ['availability_status'], unique=False)
    op.create_index(op.f('ix_alumni_current_company'), 'alumni', ['current_company'], unique=False)
    op.create_index(op.f('ix_alumni_helpfulness_score'), 'alumni', ['helpfulness_score'], unique=False)
    op.create_index(op.f('ix_alumni_industry'), 'alumni', ['industry'], unique=False)
    op.create_index(op.f('ix_alumni_location'), 'alumni', ['location'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_expires_at'), 'email_verification_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('secondary_major', sa.String(length=100), nullable=True),
    sa.Column('career_interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('preferred_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hobbies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interesting_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('resume_url', sa.String(length=255), nullable=True),
    sa.Column('reputation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_introductions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_student_career_interests', 'students', ['career_interests'], unique=False, postgresql_using='gin')
    op.create_index('idx_student_hobbies', 'students', ['hobbies'], unique=False, postgresql_using='gin')
    op.create_index('idx_student_interests', 'students', ['interests'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_students_graduation_year'), 'students', ['graduation_year'], unique=False)
    op.create_index(op.f('ix_students_major'), 'students', ['major'], unique=False)
    op.create_index(op.f('ix_students_reputation_score'), 'students', ['reputation_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_reputation_score'), table_name='students')
    op.drop_index(op.f('ix_students_major'), table_name='students')
    op.drop_index(op.f('ix_students_graduation_year'), table_name='students')
    op.drop_index('idx_student_interests', table_name='students', postgresql_using='gin')
    op.drop_index('idx_student_hobbies', table_name='students', postgresql_using='gin')
    op.drop_index('idx_student_career_interests', table_name='students', postgresql_using='gin')
    op.drop_table('students')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_expires_at'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_alumni_location'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_industry'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_helpfulness_score'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_current_company'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_availability_status'), table_name='alumni')
    op.drop_index('idx_alumni_interests', table_name='alumni', postgresql_using='gin')
    op.drop_index('idx_alumni_hobbies', table_name='alumni', postgresql_using='gin')
    op.drop_index('idx_alumni_career', table_name='alumni')
    op.drop_table('alumni')
    op.drop_index(op.f('ix_users_university_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


